name       : knotes
version    : 24.05.2
release    : 81
source     :
    - https://download.kde.org/stable/release-service/24.05.2/src/knotes-24.05.2.tar.xz : 4e6da68e1ccfd5a2fcaf038a6438bef7b671446b05a3e739787b63689016d592
homepage   : https://kde.org/applications/utilities/org.kde.knotes
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office.notes
summary    : Full featured note application
description: |
    KNotes aims to be a useful and full featured notes application for the KDE project. It tries to be as fast and lightweight as possible although including some advanced features.
builddeps  :
    - pkgconfig(x11)
    - akonadi-notes-devel
    - akonadi-search-devel
    - kcalutils-devel
    - kf6-kcmutils-devel
    - kf6-kcrash-devel
    - kf6-kdnssd-devel
    - kf6-kdoctools-devel
    - kf6-kglobalaccel-devel
    - kf6-kiconthemes-devel
    - kf6-knewstuff-devel
    - kf6-knotifications-devel
    - kf6-knotifyconfig-devel
    - kf6-kparts-devel
    - kf6-kstatusnotifieritem-devel
    - kf6-ktextwidgets-devel
    - kontactinterface-devel
    - ktextaddons-devel
    - pimcommon-devel
rundeps    :
    - kdepim-runtime
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rfv $installdir/usr/share/doc
