name       : juliaup
version    : 1.17.2
release    : 2
source     :
    - https://github.com/JuliaLang/juliaup/archive/refs/tags/v1.17.2.tar.gz : d0860697e70b5cf8c5ee8a529da82413317d996f3f1a34ff6a6fef3a4564bbd5
homepage   : https://github.com/JuliaLang/juliaup
license    : MIT
component  : programming.tools
summary    : Julia installer and version multiplexer
description: |
    A cross-platform installer for the Julia programming language.
replaces   : julia
networking : yes
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build --bin juliaup --bin julialauncher --features binjulialauncher
install    : |
    %cargo_install
    ln -s /usr/bin/julialauncher $installdir/usr/bin/julia
